### ISSUE TITLE
Merge proteomics and phospho with metadata and push to synapse

### ISSUE THREAD

**Issue by sgosline** [PNNL-CompBio/beatAMLpilotProteomics#5]
Here is a template for data merging: https://github.com/sgosline/p3/blob/main/dataProcessing/proteomicDataProcessing.Rmd 

The table should be uploaded to the http://synapse.org/ptrc (parent id for tables will be syn22128879.

After you review metadata we can discuss on this thread.

**Comment by CamiloPosso** [comment]
I finally got everything installed and the data loaded. I see the metadata has "cellLine", "Ligand", "Treatment", "Time (in minutes)" and "Sample" columns, which are currently selected by the template script. The "Sensitivity" and "TMT plex" columns are omitted.

I just uploaded the merged datables (using the default selected columns from p3 template) to the syn22128879 project.

**Comment by sgosline** [comment]
What does "Sensitivity" represent?

**Comment by CamiloPosso** [comment]
I see the column lists "Sorafenib+, Gilteritinib+" and "Gilteritinib resistant". These are apparently two types chemotherapies, so I'm thinking this column has information on what kinds of therapies are most likely to affect a patient?

**Comment by CamiloPosso** [comment]
It seems these should be included as well, but I'm not sure my guess is correct

**Comment by sgosline** [comment]
Can you please point to the files in question? I'm not sure which ones we're talking about.

**Comment by CamiloPosso** [comment]
The script proteomicsDataProcessing (from p3) is selecting a few columns from 'syn25572050', which is a metadata table with 7 total columns.

**Comment by sgosline** [comment]
Update: we're waiting for @mdnestor to finish uploading the crosstabs until we finish this.
